# PyTorch

## Tensors

This structure is used for input and output of machine Learning Networks

<https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html>

### Create from Data

In [2]:
import torch
import numpy as np

data = [[1, 1, 1], [2, 2, 2]]
tensor = torch.tensor(data)
tensor

tensor([[1, 1, 1],
        [2, 2, 2]])

### Create from numpy array

In [3]:
np_array = np.array(data)
torch.from_numpy(np_array)

tensor([[1, 1, 1],
        [2, 2, 2]], dtype=torch.int32)

### Creation functions

In [4]:
x_ones = torch.ones_like(tensor)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(tensor, dtype=float)
print(f"Random Tensor: \n {x_rand} \n")

shape = (2, 3) # only one dimensional, (number of Tensors,height,width) | (number of Tensors,width)
rand_tensor = torch.rand(shape) 
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

Random Tensor: 
 tensor([[0.8176, 0.3514, 0.3220],
        [0.4156, 0.9193, 0.0676]], dtype=torch.float64) 

Random Tensor: 
 tensor([[0.7433, 0.7026, 0.7443],
        [0.6196, 0.5457, 0.6481]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Attributes

In [5]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

if torch.cuda.is_available():
    tensor = tensor.to("cuda")
print(f"Now on gpu: {tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu
Now on gpu: cuda:0


### Functions

The Doku can be find under: <link> https://pytorch.org/docs/stable/torch.html </link>

Alter the tensor

In [6]:
tensor[:, 1] = 0
tensor

tensor([[1, 0, 1],
        [2, 0, 2]], device='cuda:0')

In [7]:
torch.cat([tensor, tensor, tensor], dim=1)

tensor([[1, 0, 1, 1, 0, 1, 1, 0, 1],
        [2, 0, 2, 2, 0, 2, 2, 0, 2]], device='cuda:0')

In [8]:
t1 = tensor.add(1)

print(f"t1:\n  {t1} \ntensor:\n  {tensor}")


t1:
  tensor([[2, 1, 2],
        [3, 1, 3]], device='cuda:0') 
tensor:
  tensor([[1, 0, 1],
        [2, 0, 2]], device='cuda:0')


it alterd only t1 because the add() function is not a in-item Function.

down below both are changed because of the ```_``` behind the function name.

In [9]:

t1 = tensor.add_(1)

print(f"t1:\n  {t1} \ntensor:\n  {tensor}")

t1:
  tensor([[2, 1, 2],
        [3, 1, 3]], device='cuda:0') 
tensor:
  tensor([[2, 1, 2],
        [3, 1, 3]], device='cuda:0')
