# PyTorch

## Tensors

### Create from Data

In [15]:
import torch
import numpy as np

data = [[1, 1, 1], [2, 2, 2]]
tensor = torch.tensor(data)
tensor

tensor([[1, 1, 1],
        [2, 2, 2]])

### Create from numpy array

In [16]:
np_array = np.array(data)
torch.from_numpy(np_array)

tensor([[1, 1, 1],
        [2, 2, 2]], dtype=torch.int32)

### Creation functions

In [17]:
x_ones = torch.ones_like(tensor)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(tensor, dtype=float)
print(f"Random Tensor: \n {x_rand} \n")

shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

Random Tensor: 
 tensor([[0.2172, 0.5053, 0.7667],
        [0.6523, 0.9218, 0.6009]], dtype=torch.float64) 

Random Tensor: 
 tensor([[0.4260, 0.3889, 0.3057],
        [0.4996, 0.3103, 0.0013]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Attributes

In [18]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

if torch.cuda.is_available():
    tensor = tensor.to("cuda")
print(f"Now on gpu: {tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


### Functions

The Doku can be find under: <link> https://pytorch.org/docs/stable/torch.html </link>

Alter the tensor

In [23]:
tensor[:, 1] = 0
tensor

tensor([[1, 0, 1],
        [2, 0, 2]])

In [24]:
torch.cat([tensor, tensor, tensor], dim=1)

tensor([[1, 0, 1, 1, 0, 1, 1, 0, 1],
        [2, 0, 2, 2, 0, 2, 2, 0, 2]])

In [33]:
t1 = tensor.add(1)

print(f"t1:\n  {t1} \ntensor:\n  {tensor}")


t1:
  tensor([[3, 2, 3],
        [4, 2, 4]]) 
tensor:
  tensor([[2, 1, 2],
        [3, 1, 3]])


it alterd only t1 because the add() function is not a in-item Function.

down below both are changed because of the ```_``` behind the function name.

In [34]:

t1 = tensor.add_(1)

print(f"t1:\n  {t1} \ntensor:\n  {tensor}")

t1:
  tensor([[3, 2, 3],
        [4, 2, 4]]) 
tensor:
  tensor([[3, 2, 3],
        [4, 2, 4]])
